name: 💡 Feature Request
description: Create a feature request
title: "[FEATURE] <descriptive title here>"
labels: [feature]
body:
- type: markdown
  attributes:
    value: |
      **Thanks for taking the time to fill out this feature description!**
- type: checkboxes
  attributes:
    label: Is there an existing feature request or discussion for this? 
    description: Please search to see if a feature request or discussion already exists for your idea.
    options:
    - label: I have searched the existing feature requests and discussions
      required: true
- type: textarea
  attributes:
    label: Problem
    description: A description of the problem you're trying to solve, including why you think this is a problemA concise description of what you're experiencing.
  validations:
    required: true
- type: textarea
  attributes:
    label: Solution
    description: An overview of the suggested solution.
  validations:
    required: true
- type: textarea
  attributes:
    label: Improvements
    description: If the feature changes current behavior, reasons why your solution is better.
  validations:
    required: false
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
